site_name: Donner
extra_css:
  - assets/extra.css
theme:
  name: material
  palette:
    scheme: donner
  favicon: assets/icons/favicon.ico
  logo: assets/icons/DonnerLogo.png

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

pages:
  - Sobre o Projeto: index.md
  - Desenho de Software (Base): 
    - Pré-Rastreabilidade: 
      - Rich Picture: pages/base/rich_picture.md
      - 5W2H: pages/base/5w2h.md
      - Diagrama de Causa-Efeito: pages/base/diagrama_de_causa-efeito.md
      - Plano de Riscos: pages/base/plano_de_riscos.md
      - Estimativas de Custos e Esforços: pages/base/estimativa_de_custos_esforços.md
    - Elicitação: 
      - Brainstorming: pages/base/brainstorming.md
      - Mapa Mental: pages/base/mapa_mental.md
      - MoSCoW: pages/base/moscow.md
    - Design Sprint: pages/base/design_sprint.md
    - BPMN: pages/base/bpmn.md
    - Personas: pages/base/personas.md
    - Protótipos: pages/base/prototipos.md
  - Sprints: 
    - Sprint 0:
      - Planning: pages/sprints/sprint0p.md
      - Review: pages/sprints/sprint0r.md
  - Políticas de Contribuição: pages/politicas.md