site_name: Donner
extra_css:
  - assets/extra.css
theme:
  name: material
  palette:
    scheme: donner
  favicon: assets/icons/DonnerLogo.png
  logo: assets/icons/DonnerLogo.png

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Sobre o Projeto: index.md
  - Desenho de Software (Base): 
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Rich Picture: pages/base/rich_picture.md
      - 5W2H: pages/base/5w2h.md
      - Diagrama de Causa-Efeito: pages/base/diagrama_de_causa-efeito.md
      - Plano de Riscos: pages/base/plano_de_riscos.md
      - Estimativas de Custos e Esforços: pages/base/estimativa_de_custos_esforços.md
      - Mapa Mental: pages/base/mapa_mental.md
      - Personas: pages/base/personas.md
      - Brainstorming: pages/base/brainstorming.md
      - StoryBoarding: pages/base/storyboard.md
      - Introspecção: pages/base/introspeccao.md
      - MoSCoW: pages/base/moscow.md
      - Design Sprint: pages/base/design_sprint.md
      - Protótipo: pages/base/prototipo.md
      - Apresentação: pages/base/video1.md
    - Módulo Processos / Metodologias / Abordagens:
      - BPMN: pages/base/bpmn.md
      - Metodologia: pages/base/metodologia.md
      - Apresentação: pages/base/video2.md
    - Iniciativas Extras: pages/base/extras_base.md
  - Desenho de Software (Modelagem):
    - Módulo Projeto Orientado a Abordagens Tradicionais:
      - Notação UML – Diagramas Estáticos:
        - Diagrama de Classe: pages/modelagem/diagrama_de_classe.md
        - Diagrama de Componentes: pages/modelagem/diagrama_de_componentes.md
        - Diagrama de Pacotes: pages/modelagem/diagrama_de_pacotes.md
        - Apresentação: pages/modelagem/video3.md
      - Notação UML – Diagramas Dinâmicos:
        - Diagrama de Atividades: pages/modelagem/diagrama_de_atividades.md
        - Diagrama de Comunicação: pages/modelagem/diagrama_de_comunicacao.md
        - Diagrama de Estados: pages/modelagem/diagrama_de_estados.md
        - Diagrama de Sequencia: pages/modelagem/diagrama_de_sequencia.md
        - Apresentação: pages/modelagem/video4.md
      - Modelagem Ágil:
        - Backlog do Produto: pages/modelagem/backlog_produto.md
        - Histórias de Usuário: pages/modelagem/historias_de_usuario.md
        - Apresentação: pages/modelagem/video5.md
    - Iniciativas Extras: pages/modelagem/extras_modelagem.md
  - Desenho de Software (Padrões de Projeto):
    - Padrões de Projeto GRASPs:
      - GRASPs: pages/padroes-de-projeto/grasps.md
      - Apresentação: pages/padroes-de-projeto/video6.md
    - Padrões de Projeto GoFs: 
      - GoFs Criacionais: pages/padroes-de-projeto/gof_criacional.md
      - GoFs Estrutural: pages/padroes-de-projeto/gof_estrutural.md
      - GoFs Comportamentais: pages/padroes-de-projeto/gof_comportamental.md
      - Apresentação: pages/padroes-de-projeto/video7.md
    - Padrões de Projeto Emergentes: 
      - Emergentes: pages/padroes-de-projeto/padrao_emergente.md
      - Apresentação: pages/padroes-de-projeto/video8.md
    - Gerência de Configuração: pages/padroes-de-projeto/gerencia_configuracao.md
    - Iniciativas Extras: pages/padroes-de-projeto/extras_padroes.md
  - Arquitetura de Software & Reutilização:
    - Estilos e Padrões Arquiteturais:
      - Documento de Arquitetura: pages/arquitetura/arquitetura.md
      - Banco de Dados: pages/arquitetura/database.md
      - Apresentação: pages/arquitetura/video9.md
    - Reutilização de Software:
      - Documento de Reutilização: pages/arquitetura/reutilizacao.md
      - Apresentação: pages/arquitetura/video10.md
    - Iniciativas Extras: pages/arquitetura/extras_arquitetura.md
  - Sprints: 
    - Sprint 0:
      - Planning: pages/sprints/sprint0/sprint0p.md
      - Review: pages/sprints/sprint0/sprint0r.md
    - Sprint 1:
      - Planning: pages/sprints/sprint1/sprint1p.md
      - Review: pages/sprints/sprint1/sprint1r.md
    - Sprint 2:
      - Planning: pages/sprints/sprint2/sprint2p.md
      - Review: pages/sprints/sprint2/sprint2r.md
    - Sprint 3:
      - Planning: pages/sprints/sprint3/sprint3p.md
      - Review: pages/sprints/sprint3/sprint3r.md
    - Sprint 4:
      - Planning: pages/sprints/sprint4/sprint4p.md
      - Review: pages/sprints/sprint4/sprint4r.md
  - Políticas de Contribuição: pages/politicas.md